export const RIGHT_PAGE_CONTENT = {
  CUSTOMER: { name: 'customer'},
  MEMBER: { name: 'member'},
  RANKING: { name: 'ranking' },
  POINTS: { name: 'points' },
  TREND: { name: 'name' },
  REVENUE: { name: 'revenue' },
  SUMMARY: { name: 'summary' },
  PRIZE: { name: 'prize' },
  EXPIRED_POINTS: { name: 'expired-points' },
  NEAR_EXPIRED_POINTS: { name: 'near-expired-points' },
  UNUSUAL_TRANSACTION: { name: 'unusual-transaction' },
  ADJUST_TRANSACTION: { name: 'adjust-transaction' },
  NETWORK_GIFT_EXCHANGE: { name: 'network-gift-exchange' },
  MEMBER_RANKS: { name: 'member-ranks' },
  MEMBER_RANK_DETAILS: { name: 'member-rank-details' },
  ACCOUNT_BALANCE: { name: 'account-balance' },
  ACCCOUNT_BALANCE_DETAILS: { name: 'acccount-balance-details' },
}